import { motion } from 'framer-motion';
import { useInView } from 'framer-motion';
import { useRef } from 'react';
import { Play, Eye, Clock } from 'lucide-react';

const showcaseVideos = [
  {
    title: 'Epic Space Journey',
    style: 'Cinematic',
    duration: '30s',
    views: '1.2M',
    image: 'https://images.pexels.com/photos/586030/pexels-photo-586030.jpeg?w=600&h=400&fit=crop',
    prompt: 'An astronaut floating through a colorful nebula with distant galaxies',
  },
  {
    title: 'Samurai Duel',
    style: 'Anime',
    duration: '15s',
    views: '892K',
    image: 'https://images.pexels.com/photos/3109671/pexels-photo-3109671.jpeg?w=600&h=400&fit=crop',
    prompt: 'Two samurai warriors in an epic battle at sunset in feudal Japan',
  },
  {
    title: 'Product Launch',
    style: 'Marketing',
    duration: '60s',
    views: '2.1M',
    image: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?w=600&h=400&fit=crop',
    prompt: 'Sleek modern smartphone product reveal with dynamic lighting',
  },
  {
    title: 'Nature Documentary',
    style: 'Documentary',
    duration: '2m',
    views: '540K',
    image: 'https://images.pexels.com/photos/1591447/pexels-photo-1591447.jpeg?w=600&h=400&fit=crop',
    prompt: 'A majestic eagle soaring over snow-capped mountain peaks',
  },
  {
    title: 'Fantasy World',
    style: 'Fantasy',
    duration: '45s',
    views: '3.4M',
    image: 'https://images.pexels.com/photos/1366957/pexels-photo-1366957.jpeg?w=600&h=400&fit=crop',
    prompt: 'A magical floating island with waterfalls cascading into the clouds',
  },
  {
    title: 'Tech Tutorial',
    style: 'Educational',
    duration: '3m',
    views: '678K',
    image: 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?w=600&h=400&fit=crop',
    prompt: 'How AI neural networks process visual information step by step',
  },
];

const styleColors: Record<string, string> = {
  Cinematic: 'bg-primary-500/15 text-primary-300',
  Anime: 'bg-pink-500/15 text-pink-300',
  Marketing: 'bg-green-500/15 text-green-300',
  Documentary: 'bg-amber-500/15 text-amber-300',
  Fantasy: 'bg-secondary-500/15 text-secondary-300',
  Educational: 'bg-accent-500/15 text-accent-300',
};

export default function Showcase() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: '-100px' });

  return (
    <section className="py-24 bg-dark-950/50 relative" ref={ref}>
      <div className="absolute inset-0 bg-gradient-radial from-secondary-900/20 via-transparent to-transparent" />
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.5 }}
          className="text-center mb-16"
        >
          <span className="inline-flex items-center gap-2 glass border border-secondary-500/30 text-secondary-400 text-sm font-medium px-4 py-2 rounded-full mb-4">
            <Play className="w-4 h-4" />
            AI Video Showcase
          </span>
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold font-poppins text-white mb-4">
            See What's Possible with
            <br />
            <span className="gradient-text">VisionFlow AI</span>
          </h2>
          <p className="text-dark-400 text-lg max-w-2xl mx-auto">
            Real videos generated by our users. Every frame crafted by artificial intelligence.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {showcaseVideos.map((video, i) => (
            <motion.div
              key={video.title}
              initial={{ opacity: 0, y: 40 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.5, delay: i * 0.08 }}
              whileHover={{ y: -8 }}
              className="group glass-card overflow-hidden p-0 border border-white/5 hover:border-primary-500/30 transition-all duration-300"
            >
              <div className="relative aspect-video overflow-hidden">
                <img
                  src={video.image}
                  alt={video.title}
                  className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-dark-900 via-transparent to-transparent" />
                <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                  <div className="w-14 h-14 rounded-full bg-white/20 backdrop-blur-sm border border-white/30 flex items-center justify-center">
                    <Play className="w-6 h-6 text-white fill-white ml-0.5" />
                  </div>
                </div>
                <div className="absolute top-3 left-3">
                  <span className={`text-xs px-2 py-1 rounded-full font-medium ${styleColors[video.style]}`}>
                    {video.style}
                  </span>
                </div>
                <div className="absolute top-3 right-3 flex items-center gap-1 glass px-2 py-1 rounded-full text-xs text-dark-300">
                  <Clock className="w-3 h-3" />
                  {video.duration}
                </div>
              </div>
              <div className="p-4">
                <h3 className="text-white font-semibold font-poppins mb-1">{video.title}</h3>
                <p className="text-dark-400 text-xs leading-relaxed mb-3 line-clamp-2">"{video.prompt}"</p>
                <div className="flex items-center gap-1 text-dark-500 text-xs">
                  <Eye className="w-3 h-3" />
                  <span>{video.views} views</span>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
